# -*- coding: utf-8 -*-
"""Rnn Covid.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iFbVXVCZc4O_2WpfMkORj5wprrvk24uO
"""

import tensorflow as tf

# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import datetime

# Importing the training set
dataset = pd.read_excel('Rolling Averages.xlsx')

total_set =dataset.iloc[:,3:4].values
print(total_set,total_set.shape)

test_size=7
train_dates=dataset['Date'].iloc[:-test_size]
train_dates=[date.date() for date in train_dates]
test_dates=dataset['Date'].iloc[-test_size:]
test_dates=[date.date() for date in test_dates]
last_day = dataset['Date'].iloc[-1].date()

training_set=total_set[:-test_size]
testing_set=total_set[-test_size:]
print("train=", training_set.shape)
print("test=", testing_set.shape)

from sklearn.preprocessing import MinMaxScaler
sc = MinMaxScaler(feature_range = (0, 1))
training_set_scaled =sc.fit_transform(training_set)
testing_set_scaled =sc.transform(testing_set)
print(training_set_scaled.shape)
print(testing_set_scaled.shape)

window= 3

X_train = []
y_train = []
for i in range(window, len(training_set)):
    X_train.append(training_set_scaled[i-window:i, 0])
    y_train.append(training_set_scaled[i, 0])
X_train, y_train = np.array(X_train), np.array(y_train)

# Reshaping
X_train = np.reshape(X_train, (X_train.shape[0], X_train.shape[1], 1))

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dropout
from tensorflow.keras.callbacks import ModelCheckpoint
from tensorflow.keras.models import load_model

regressor = Sequential()

# Adding the first LSTM layer and some Dropout regularisation
regressor.add(LSTM(units = 500, return_sequences = True, input_shape = (X_train.shape[1], X_train.shape[2])))
regressor.add(Dropout(0.2))

regressor.add(LSTM(units = 500, return_sequences = True))
regressor.add(Dropout(0.2))

regressor.add(LSTM(units = 500, return_sequences = False))
regressor.add(Dropout(0.2))

# Adding the output layer
regressor.add(Dense(units = 1))
regressor.compile(optimizer = 'adam', loss = 'mean_squared_error')

mc = ModelCheckpoint('best_model_daily.h5', monitor='loss', mode='min', verbose=1, save_best_only=True)

regressor.fit(X_train, y_train, epochs = 30,  batch_size = 4, callbacks=[mc])

regressor=load_model('best_model_daily.h5')



X_test = []
y_test=[]
for i in range(window,len(testing_set_scaled)):
    X_test.append(testing_set_scaled[i-window:i, 0])
    y_test.append(testing_set[i, 0])
X_test = np.array(X_test)
X_test = np.reshape(X_test, (X_test.shape[0], X_test.shape[1], 1))

print(X_test.shape)

y_pred = regressor.predict(X_test)
y_pred = sc.inverse_transform(y_pred)
print(y_pred.shape)

y_pred_train = regressor.predict(X_train)
y_pred_train = sc.inverse_transform(y_pred_train)
print(y_pred_train.shape)

train_y=y_train.reshape(-1,1)
train_y=sc.inverse_transform(train_y)



# Visualising the train results
plt.rcParams['figure.figsize']= 20,10

plt.plot(train_y, color = 'red', label = 'Real Daily cases')
plt.plot(y_pred_train, color = 'blue', label = 'Predicted Daily cases')
plt.title('Daily Cases Trend Training')
plt.xticks(list(range(0,len(y_pred_train))), train_dates, rotation='vertical')
plt.xlabel('Date')
plt.ylabel('No. of Cases')
plt.legend()
plt.show()

# Visualising the test results
plt.plot(y_test, color = 'red', label = 'Real Daily cases')
plt.plot(y_pred, color = 'blue', label = 'Predicted Daily cases')
plt.title('Daily Cases Trend Testing')
plt.xticks(list(range(0,len(y_pred))), test_dates, rotation='vertical')
plt.xlabel('Date')
plt.ylabel('No. of Cases')
plt.legend()
plt.show()

predict_for=X_test[-1]

predictions=list()
dates=list()
for i in range(7):
    test=np.reshape(predict_for, (1,predict_for.shape[0],predict_for.shape[1]))
    test=regressor.predict(test)
    dates.append(last_day+datetime.timedelta(days=i+1))
    predictions.append(sc.inverse_transform(test)[0])
    predict_for=np.array([predict_for[1],predict_for[2],test[0]])

predictions=np.array(predictions)

# Visualising the results
plt.plot(predictions, color = 'blue', label = 'Predicted Daily cases')
plt.xticks(list(range(len(predictions))),dates,rotation='vertical')
plt.title('Cases Daily Future')
plt.xlabel('Date')
plt.ylabel('No. of Cases')
plt.legend()
plt.show()

import pandas as pd
future_predictions= pd.DataFrame(np.append(np.array(dates).reshape(-1,1),predictions, axis=1))
future_predictions.columns=['Date','Predictions']

future_predictions.to_excel("Future Daily Predictions.xlsx", index=False)